apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api
  namespace: atlasbank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products-api
  template:
    metadata:
      labels:
        app: products-api
    spec:
      containers:
        - name: products-api
          image: atlasbank/products-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: atlasbank-config
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: products-connection-string
---
apiVersion: v1
kind: Service
metadata:
  name: products-api-service
  namespace: atlasbank
spec:
  selector:
    app: products-api
  ports:
    - port: 80
      targetPort: 8080
