apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: atlasbank
type: Opaque
stringData:
  accounts-connection-string: "Host=postgres-service;Database=atlasbank_accounts;Username=postgres;Password=postgres"
  transactions-connection-string: "Host=postgres-service;Database=atlasbank_transactions;Username=postgres;Password=postgres"
  products-connection-string: "Host=postgres-service;Database=atlasbank_products;Username=postgres;Password=postgres"
  compliance-connection-string: "Host=postgres-service;Database=atlasbank_compliance;Username=postgres;Password=postgres"
  tenancy-connection-string: "Host=postgres-service;Database=atlasbank_tenancy;Username=postgres;Password=postgres"
  jwt-secret: "YourSuperSecretKeyThatIsAtLeast32CharactersLong!"
